name: Deploy Website

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v2
    - uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.CREDENTIAL_JSON }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: build
      run: npm run build
    - name: install
      run: 
    - name: firebase deploy
      run: |
        npx firebase use "okazaki-shogo-website"
        npx firebase target:apply hosting firebase.json "https://okazaki-shogo-website.web.app"
        npx firebase deploy --only hosting: firebase.json