name: Deploy Website

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.CREDENTIAL_JSON }}
      - name: firebase deploy
        run: npx firebase deploy